project_name: panel
builds:
  -
    id: panel
    binary: panel
    env:
      - CGO_ENABLED=0
      - GOPROXY=https://goproxy.cn,direct
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
    ldflags:
      - -s -w --extldflags "-static -fpic"
archives:
  -
    id: panel-archive
    builds:
      - panel
    format: zip
    wrap_in_directory: false
    strip_parent_binary_folder: true
    files:
      - LICENSE
      - docs/*
      - public/*
      - storage/*
      - database/*
      - scripts/*
      - panel-example.conf

gitlab_urls:
  api: https://git.haozi.net/api/v4/
  download: https://git.haozi.net

  # set to true if you use a self-signed certificate
  skip_tls_verify: false

  # set to true if you want to upload to the Package Registry rather than attachments
  # Only works with GitLab 13.5+
  #
  # Since: v1.3
  use_package_registry: false

  # Set this if you set GITLAB_TOKEN to the value of CI_JOB_TOKEN.
  #
  # Since: v1.11
  use_job_token: true
