basePath: /api
definitions:
  request.UserLogin:
    properties:
      password:
        maxLength: 255
        minLength: 6
        type: string
      username:
        maxLength: 255
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  service.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
info:
  contact:
    email: admin@haozi.net
    name: 耗子科技
  description: 耗子面板的 API 信息
  license:
    name: GNU Affero General Public License v3
  title: 耗子面板 API
  version: "2"
paths:
  /info/checkUpdate:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 检查更新
      tags:
      - 信息服务
  /info/countInfo:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 统计信息
      tags:
      - 信息服务
  /info/homePlugins:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 首页插件
      tags:
      - 信息服务
  /info/installedDbAndPhp:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 已安装的数据库和PHP
      tags:
      - 信息服务
  /info/nowMonitor:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 实时监控
      tags:
      - 信息服务
  /info/panel:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 面板信息
      tags:
      - 信息服务
  /info/restart:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 重启面板
      tags:
      - 信息服务
  /info/systemInfo:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 系统信息
      tags:
      - 信息服务
  /info/update:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 更新面板
      tags:
      - 信息服务
  /info/updateInfo:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 版本更新信息
      tags:
      - 信息服务
  /user/info/{id}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 用户信息
      tags:
      - 用户服务
  /user/isLogin:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 是否登录
      tags:
      - 用户服务
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 登录
      tags:
      - 用户服务
  /user/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SuccessResponse'
      summary: 登出
      tags:
      - 用户服务
securityDefinitions:
  BearerToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
