name: Issue Auto Reply
on:
  issues:
    types: [ labeled ]
permissions:
  contents: read
jobs:
  issue-reply:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: ✏️ Feature
        if: github.event.label.name == '✏️ Feature'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.event.issue.user.login }} 👋
            
            我们认为您的建议非常有价值！欢迎提交 PR，请包含相应的测试用例、文档等，并确保 CI 通过，感谢和期待您的贡献！
            We think your suggestion is very valuable! Welcome to submit a PR, please include test cases, documentation, etc., and ensure that the CI is passed, thank you and look forward to your contribution! 
            
            ![干](https://github.com/TheTNB/panel/assets/115467771/fb04debf-3f4c-4fac-a0b8-c3455f8e57a0)
      - name: ☢️ Bug
        if: github.event.label.name == '☢️ Bug'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.event.issue.user.login }} 👋
            
            我们认为您的反馈非常有价值！欢迎提交 PR，请包含相应的测试用例、文档等，并确保 CI 通过，感谢和期待您的贡献！
            We think your feedback is very valuable! Welcome to submit a PR, please include test cases, documentation, etc., and ensure that the CI is passed, thank you and look forward to your contribution! 
            
            ![干](https://github.com/TheTNB/panel/assets/115467771/fb04debf-3f4c-4fac-a0b8-c3455f8e57a0)