name: Lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: golanci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false
      - uses: golangci/golangci-lint-action@v6
        with:
          skip-cache: true
          version: latest
          args: --timeout=30m ./...
