name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: sudo apt-get install -y curl jq
      - name: Set up environment
        run: |
          cp panel-example.conf .env
          echo "DB_FILE=$(pwd)/storage/panel.db" >> .env
          go run . artisan key:generate
          go run . artisan migrate
      - name: Run tests
        run: go test ./...
