name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install dependencies
        run: sudo apt-get install -y curl jq
      - name: Set up environment
        run: |
          cp config/config.example.yml config/config.yml
      - name: Run tests
        run: go test ./...
